import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { QueryProvider, ThemeProvider } from './providers'
import { Toaster } from '@/components/ui/toaster'
import TopNavBar from '@/components/TopNavBar'
import { ReturnToTopButton } from '@/components/return-to-top-button'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<QueryProvider>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem
						disableTransitionOnChange
					>
						<TopNavBar />
						{children}
						<ReturnToTopButton />
						<Toaster />
					</ThemeProvider>
				</QueryProvider>
			</body>
		</html>
	)
}
